const express = require("express")
const router = express.Router()
const { createPatient, getPatients } = require("../controllers/patient")
router.post("/", createPatient)
router.get("/", getPatients)